apiVersion: apps/v1
kind: Deployment
metadata:
    name: madome-debug
spec:
    selector:
        matchLabels:
            app: madome-debug
    template:
        metadata:
            labels:
                app: madome-debug
        spec:
            containers:
                - name: madome-debug
                  image: madome-debug:latest
                  imagePullPolicy: Never
                  resources:
                      limits:
                          memory: "128Mi"
                          cpu: "250m"
                  ports:
                      - containerPort: 3112
                  env:
                      - name: DEBUG_URL
                        value: http://madome-e2e
---
apiVersion: v1
kind: Service
metadata:
    name: madome-debug
spec:
    type: NodePort
    selector:
        app: madome-debug
    ports:
        - port: 3112
          protocol: TCP
          nodePort: 32148
