apiVersion: apps/v1
kind: Deployment
metadata:
    name: madome-e2e-channel
spec:
    selector:
        matchLabels:
            app: madome-e2e-channel
    template:
        metadata:
            labels:
                app: madome-e2e-channel
        spec:
            containers:
                - name: madome-e2e-channel
                  image: madome-e2e-channel:latest
                  imagePullPolicy: Never
                  resources:
                      limits:
                          memory: "128Mi"
                          cpu: "250m"
                  ports:
                      - containerPort: 3112
                  env:
                      - name: E2E_TESTING_URL
                        value: http://madome-e2e
---
apiVersion: v1
kind: Service
metadata:
    name: madome-e2e-channel
spec:
    type: NodePort
    selector:
        app: madome-e2e-channel
    ports:
        - port: 3112
          protocol: TCP
          nodePort: 32148
